### PR TITLE
feat: Restyle OG to accomodate large numbers

### PR DESCRIPTION
**Pull request by Namchee**
## Overview

This pull request attempts to fix the OG image number overflow by restyling the content to a column-based flexbox.
This pull request also resizes image resolution to perfect `2:1` ratio.

## Sample Image

og

## Changes

- [x] `og.ts`
- [x] `template.ts`

_Any other changes shouldn't be harmful._

### CODE REVIEW

**Comment by spiritbro1** [comment]
cool bro ini sudah jadi? yang conflict itu biarin bro itu soalnya kena auto commit github action jadi pilih yang current aja atau yang lama buat mbenerinnya

**Comment by Namchee** [comment]
@spiritbro1 Sudah, paling tinggal tunggu lampu hijaunya mathdroid.

**Comment by spiritbro1** [comment]
> @spiritbro1 Sudah, paling tinggal tunggu lampu hijaunya mathdroid.

cool

**Comment by spiritbro1** [comment]
> ## Overview
> This pull request attempts to fix the OG image number overflow by restyling the content to a column-based flexbox.
> This pull request also resizes image resolution to perfect `2:1` ratio.
> 
> ## Sample Image
> og
> 
> ## Changes
> * [x]  `og.ts`
> * [x]  `template.ts`
> 
> _Any other changes shouldn't be harmful._

anjay bro cool

**Comment by spiritbro1** [comment]
image

approved by @mathdroid

**Comment by spiritbro1** [comment]
@Namchee bisa tolong di resolve pilih yang current push ya

**Comment by Namchee** [comment]
@spiritbro1 Should be alright now

**Comment by spiritbro1** [comment]
THANKS BRO MERGEDDDDD YEAH

**Pull request merged**
